spring:
  application:
    name: user-service
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
server:
  port: 8888

hystrix:
  metrics:
    enabled: true

management:
  endpoint:
    health:
      enabled: true
    hystrix:
      stream:
        enabled: true
  endpoints:
    web:
      exposure:
        include: hystrix.stream,health,info